### ISSUE TITLE
Add teams section to get members of a team

### ISSUE THREAD

**Issue by kyoshidajp** [potch8228/pubkey#2]
# Summary

Add teams section to get members of a team.

# Changes

I guess `settings.yml` format will be the following.

```yml
users:
    - id: user1
    - id: user2
teams:
    - id: team1
    - id: team2
```

And it would be able to get members to call API.
https://developer.github.com/v3/teams/members/#list-team-members
